#!/usr/bin/env python3
import os
import sys
import pickle
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

from today_vn_news.logger import logger
from today_vn_news.exceptions import UploadError

"""
YouTube 업로드 모듈 (YouTube Data API v3 Wrapper)
- 목적: 생성된 뉴스 영상을 유튜브 채널에 자동 업로드
- 상세 사양: ContextFile.md 3.1 (인프라) 참조
- 필요 파일: client_secrets.json (OAuth2 자격 증명)
"""

# YouTube Data API v3 scopes
SCOPES = [
    'https://www.googleapis.com/auth/youtube.upload',
    'https://www.googleapis.com/auth/youtube'
]

# 기본 재생 목록 ID (오늘의 베트남 뉴스)
DEFAULT_PLAYLIST_ID = "PLzMxB6D1eypIA_JNasD_MNISMEUtMbHvK"

def get_authenticated_service(data_dir: str = "data"):
    """
    OAuth2 인증을 통해 유튜브 API 서비스 객체 생성 및 반환

    Args:
        data_dir: 데이터 디렉토리 경로 (토큰 파일 위치)
                   인증 파일(client_secrets.json)은 프로젝트 루트에서 찾습니다.
    """
    credentials = None
    # 토큰은 data_dir에 저장
    token_path = os.path.join(data_dir, 'token.pickle')
    # 인증 파일은 프로젝트 루트에서 찾음
    secrets_path = 'client_secrets.json'

    # 기존 토큰 로드
    if os.path.exists(token_path) and os.path.getsize(token_path) > 0:
        try:
            with open(token_path, 'rb') as token:
                credentials = pickle.load(token)
        except (EOFError, pickle.UnpicklingError) as e:
            logger.warning(f"토큰 파일 로드 실패: {e}")
            credentials = None

    # 토큰이 없거나 만료된 경우 인증 수행
    if not credentials or not credentials.valid:
        if credentials and credentials.expired and credentials.refresh_token:
            try:
                credentials.refresh(Request())
                logger.info("토큰 갱신 완료")
            except Exception as e:
                logger.error(f"토큰 갱신 실패: {e}")
                raise UploadError(f"토큰 갱신 실패: {e}")
        else:
            if not os.path.exists(secrets_path):
                logger.error(f"'{secrets_path}' 파일이 필요합니다. Google Cloud Console에서 다운로드하여 루트에 배치해 주세요.")
                raise UploadError(f"'{secrets_path}' 파일이 필요합니다.")

            flow = InstalledAppFlow.from_client_secrets_file(secrets_path, SCOPES)
            # 서버 환경이나 원격 환경을 고려하여 open_browser=False 설정
            try:
                credentials = flow.run_local_server(port=58080, open_browser=False)
            except OSError as e:
                if e.errno == 48:
                    logger.error("58080 포트가 이미 사용 중입니다.")
                    logger.error("'lsof -ti :58080 | xargs kill -9' 명령어로 기존 프로세스를 종료 후 다시 시도해 주세요.")
                    raise UploadError("58080 포트가 이미 사용 중입니다.")
                raise UploadError(f"OAuth 인증 중 오류 발생: {e}")

        # 토큰 저장
        try:
            with open(token_path, 'wb') as token:
                pickle.dump(credentials, token)
        except Exception as e:
            logger.error(f"토큰 저장 실패: {e}")
            raise UploadError(f"토큰 저장 실패: {e}")

    return build('youtube', 'v3', credentials=credentials)

def add_video_to_playlist(youtube, video_id, playlist_id):
    """
    영상을 특정 재생 목록에 추가
    """
    logger.info(f"재생 목록에 추가 중: {playlist_id}")
    try:
        request = youtube.playlistItems().insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {
                        "kind": "youtube#video",
                        "videoId": video_id
                    }
                }
            }
        )
        response = request.execute()
        logger.info(f"재생 목록 추가 완료! Item ID: {response.get('id')}")
        return True
    except Exception as e:
        logger.error(f"재생 목록 추가 중 오류 발생: {str(e)}")
        raise UploadError(f"재생 목록 추가 중 오류 발생: {str(e)}")

def upload_video(yymmdd: str, data_dir: str = "data"):
    """
    영상을 유튜브에 업로드

    Args:
        yymmdd: 타임스탬프 (YYYYMMDD_HHMM 형식)
        data_dir: 데이터 디렉토리 경로
    """
    file_path = os.path.join(data_dir, f"{yymmdd}_final.mp4")
    if not os.path.exists(file_path):
        logger.error(f"업로드할 파일을 찾을 수 없습니다: {file_path}")
        raise UploadError(f"업로드할 파일을 찾을 수 없습니다: {file_path}")

    try:
        youtube = get_authenticated_service(data_dir)
    except UploadError:
        raise
    except Exception as e:
        logger.error(f"유튜브 인증 실패: {e}")
        raise UploadError(f"유튜브 인증 실패: {e}")

    logger.info(f"유튜브 업로드 시작: {file_path}")

    # 영상 정보 설정 (마크다운에서 제목 추출 로직 추가 권장)
    title = f"Today VN IT News - {yymmdd}"
    description = f"Today's Vietnam IT News summary for {yymmdd}.\nGenerated by today-vn-news automation pipeline."
    tags = ["vietnam", "news", "it", "automation", "tts"]

    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': tags,
            'categoryId': '22'  # People & Blogs
        },
        'status': {
            'privacyStatus': 'unlisted'  # 초기 업로드는 비공개(unlisted) 권장
        }
    }

    media = MediaFileUpload(
        file_path,
        chunksize=-1,
        resumable=True,
        mimetype='video/mp4'
    )

    request = youtube.videos().insert(
        part=','.join(body.keys()),
        body=body,
        media_body=media
    )

    response = None
    try:
        while response is None:
            status, response = request.next_chunk()
            if status:
                logger.info(f"업로드 진행 중: {int(status.progress() * 100)}%")
    except Exception as e:
        logger.error(f"업로드 중 오류 발생: {str(e)}")
        raise UploadError(f"업로드 중 오류 발생: {str(e)}")

    video_id = response.get('id')
    logger.info(f"업로드 완료! Video ID: {video_id}")

    # 재생 목록에 추가
    if video_id:
        try:
            add_video_to_playlist(youtube, video_id, DEFAULT_PLAYLIST_ID)
        except UploadError:
            logger.warning("재생 목록 추가 실패 (업로드는 완료됨)")

    return True

if __name__ == "__main__":
    if len(sys.argv) > 1:
        upload_video(sys.argv[1])
    else:
        upload_video("260106")
