#!/usr/bin/env python3
import os
import sys
import pickle
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

"""
YouTube 업로드 모듈 (YouTube Data API v3 Wrapper)
- 목적: 생성된 뉴스 영상을 유튜브 채널에 자동 업로드
- 상세 사양: ContextFile.md 3.1, 4단계 배포 참조
- 필요 파일: client_secrets.json (OAuth2 자격 증명)
"""

# YouTube Data API v3 scope
SCOPES = ['https://www.googleapis.com/auth/youtube.upload']

def get_authenticated_service():
    """
    OAuth2 인증을 통해 유튜브 API 서비스 객체 생성 및 반환
    """
    credentials = None
    token_path = 'token.pickle'
    secrets_path = 'client_secrets.json'

    # 기존 토큰 로드
    if os.path.exists(token_path):
        with open(token_path, 'rb') as token:
            credentials = pickle.load(token)

    # 토큰이 없거나 만료된 경우 인증 수행
    if not credentials or not credentials.valid:
        if credentials and credentials.expired and credentials.refresh_token:
            credentials.refresh(Request())
        else:
            if not os.path.exists(secrets_path):
                print(f"[!] '{secrets_path}' 파일이 필요합니다. Google Cloud Console에서 다운로드하여 루트에 배치해 주세요.")
                return None
            
            flow = InstalledAppFlow.from_client_secrets_file(secrets_path, SCOPES)
            credentials = flow.run_local_server(port=0)

        # 토큰 저장
        with open(token_path, 'wb') as token:
            pickle.dump(credentials, token)

    return build('youtube', 'v3', credentials=credentials)

def upload_video(yymmdd: str, data_dir: str = "data"):
    """
    영상을 유튜브에 업로드
    """
    file_path = os.path.join(data_dir, f"{yymmdd}_final.mp4")
    if not os.path.exists(file_path):
        print(f"[!] 업로드할 파일을 찾을 수 없습니다: {file_path}")
        return False

    youtube = get_authenticated_service()
    if not youtube:
        return False

    print(f"[*] 유튜브 업로드 시작: {file_path}")

    # 영상 정보 설정 (마크다운에서 제목 추출 로직 추가 권장)
    title = f"Today VN IT News - {yymmdd}"
    description = f"Today's Vietnam IT News summary for {yymmdd}.\nGenerated by today-vn-news automation pipeline."
    tags = ["vietnam", "news", "it", "automation", "tts"]

    body = {
        'snippet': {
            'title': title,
            'description': description,
            'tags': tags,
            'categoryId': '22'  # People & Blogs
        },
        'status': {
            'privacyStatus': 'unlisted'  # 초기 업로드는 비공개(unlisted) 권장
        }
    }

    media = MediaFileUpload(
        file_path,
        chunksize=-1,
        resumable=True,
        mimetype='video/mp4'
    )

    request = youtube.videos().insert(
        part=','.join(body.keys()),
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"[*] 업로드 진행 중: {int(status.progress() * 100)}%")

    print(f"[+] 업로드 완료! Video ID: {response.get('id')}")
    return True

if __name__ == "__main__":
    if len(sys.argv) > 1:
        upload_video(sys.argv[1])
    else:
        upload_video("260106")
